# Generated by Django 6.0.4 on 2026-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='headers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='raw_headers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
