# Generated by Django 6.0.4 on 2026-04-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactsubmission_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='webhook_sent',
        ),
    ]
