# Generated by Django 6.0.4 on 2026-04-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(help_text='All submissions are delivered here', max_length=254)),
                ('email_bcc', models.TextField(blank=True, help_text='Comma-separated BCC addresses — hidden from primary recipient')),
                ('autoresponse_subject', models.CharField(default='Thanks for your message!', max_length=200)),
                ('autoresponse_body', models.TextField(default='Hi {name},\n\nWe received your message and will get back to you soon.\n\nBest regards,\nThe Team')),
                ('redirect_url', models.URLField(blank=True, help_text='Custom thank-you page URL. Leave blank for built-in page.')),
                ('webhook_url', models.URLField(blank=True, help_text='POST JSON here on every submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
