# Generated by Django 6.0.4 on 2026-04-20 11:29

import uuid
from django.db import migrations, models


def generate_unique_identifiers(apps, schema_editor):
    UserFormConfig = apps.get_model('accounts', 'UserFormConfig')
    for config in UserFormConfig.objects.all():
        if not config.unique_identifier:
            config.unique_identifier = uuid.uuid4().hex[:8].upper()
            config.save(update_fields=['unique_identifier'])


def reverse_unique_identifiers(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformconfig',
            name='unique_identifier',
            field=models.CharField(blank=True, help_text='Share this code to receive form submissions', max_length=8),
        ),
        migrations.RunPython(generate_unique_identifiers, reverse_unique_identifiers),
        migrations.AlterField(
            model_name='userformconfig',
            name='unique_identifier',
            field=models.CharField(blank=True, help_text='Share this code to receive form submissions', max_length=8, unique=True),
        ),
    ]
