# Generated by Django 6.0.4 on 2026-04-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userformconfig_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformconfig',
            name='webhook_url',
        ),
    ]
