# Generated by Django 6.0.4 on 2026-04-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userformconfig_webhook_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformconfig',
            name='redirect_url',
        ),
    ]
